import Image from 'next/image'
import Head from 'next/head'
import { createClient } from 'next-sanity'
import imageUrlBuilder from '@sanity/image-url'
import styles from '../../styles/Home.module.css'
import { Box, Container } from '@mui/system'
import { Typography } from '@mui/material'

export default function Supercars({ supercar }) {
  return (
    <>
      <Head>
        <title>{supercar.name}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='initial-scale=1, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container>
        <Box sx={{ py: 2 }}>
          <Typography gutterBottom={false} variant='h3' component='div'>
            {supercar.name}
          </Typography>
        </Box>
        <Image src={urlFor(supercar.images).url()} alt='supercar' width={500} height={300} layout='responsive' />
        <Box sx={{ my: 2 }}>
          <Typography gutterBottom={false} variant='h6' component='div'>
            {supercar.detail}
          </Typography>
        </Box>
      </Container>
    </>
  )
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION,
  useCdn: false,
})

const builder = imageUrlBuilder(client)

function urlFor(source) {
  return builder.image(source)
}

export async function getStaticPaths() {
  const supercars = await client.fetch(`*[_type == "supercars"]`)

  const paths = supercars.map(supercar => ({
    params: { id: supercar._id },
  }))

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {
  const supercars = await client.fetch(`*[_type == "supercars" && _id >= "${params.id}"]`)
  if (supercars.length > 0) {
    const supercar = supercars[0]
    return {
      props: {
        supercar,
      },
    }
  }
  return {
    props: {},
  }
}
