import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { createClient } from 'next-sanity'
import imageUrlBuilder from '@sanity/image-url'

export default function Home({ supercars }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Supercars</title>
        <meta name='description' content='Generated by nckvDev' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Supercars</h1>
        {supercars.length > 0 && (
          <ul>
            {supercars.map(supercar => (
              <li key={supercar._id}>
                {supercar?.name} <br />
                {supercar?.detail} <br />
                <Image src={urlFor(supercar.images).url()} alt='supercar' width={500} height={300} />
                <Link href={`/supercars/${supercar._id}`}>See more</Link>
              </li>
            ))}
          </ul>
        )}
      </main>
    </div>
  )
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION,
  useCdn: false,
})

const builder = imageUrlBuilder(client)

function urlFor(source) {
  return builder.image(source)
}

export async function getStaticProps() {
  const supercars = await client.fetch(`*[_type == "supercars"]`)
  return {
    props: {
      supercars,
    },
  }
}
