import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import { createClient } from 'next-sanity'
import imageUrlBuilder from '@sanity/image-url'
import { Box, Button, Card, CardActionArea, CardContent, CardMedia, Grid, Typography } from '@mui/material'
import { Container } from '@mui/system'
import React from 'react'

export default function Home({ supercars }) {
  return (
    <>
      <Head>
        <title>Supercars</title>
        <meta name='description' content='Generated by nckvDev' />
        <meta name='viewport' content='initial-scale=1, width=device-width' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography
        gutterBottom={true}
        variant='h1'
        align='center'
        sx={{ marginTop: 2, fontWeight: 400, letterSpacing: 2 }}
      >
        Supercars
      </Typography>

      <Container maxWidth='lg'>
        {supercars.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Grid container spacing={2}>
              <React.Fragment>
                {supercars.map(supercar => (
                  <Grid item={true} xs={12} md={6} lg={4} key={supercar._id}>
                    <Card>
                      <Link href={`/supercars/${supercar._id}`}>
                        <CardActionArea>
                          <CardMedia
                            component='img'
                            height='250'
                            image={urlFor(supercar.images).url()}
                            alt='green iguana'
                          />
                          <CardContent>
                            <Typography gutterBottom={false} variant='h5' component='div' align='center'>
                              {supercar?.name}
                            </Typography>
                          </CardContent>
                        </CardActionArea>
                      </Link>
                    </Card>
                  </Grid>
                ))}
              </React.Fragment>
            </Grid>
          </Box>
        )}
      </Container>
    </>
  )
}

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET,
  apiVersion: process.env.NEXT_PUBLIC_SANITY_API_VERSION,
  useCdn: false,
})

const builder = imageUrlBuilder(client)

function urlFor(source) {
  return builder.image(source)
}

export async function getStaticProps() {
  const supercars = await client.fetch(`*[_type == "supercars"]`)
  return {
    props: {
      supercars,
    },
  }
}
